### ISSUE TITLE
Harmony Patches applied for incompatible mods

### ISSUE THREAD

**Issue by Ashiepaws** [Hacktix/Winch#21]
Harmony Patches defined in mods are always applied, no matter whether Winch considers the mod compatible or not. This is due to the fact that Harmony Patching occurs immediately after assemblies are loaded, before any meta validation is done.

**Comment by bdlm-dev** [comment]
Should be relatively easy to fix by adding a flag to the ModAssembly class, then just checking that when it tries to patch?

**Comment by Ashiepaws** [comment]
Yep, that was the idea. Mainly just created the issue so I wouldn't forget 😅
